[build]
publish = "public"
command = "echo 'no build necessary'"
functions = "functions"


[[plugins]]
package = "@netlify/plugin-sitemap"

 [plugins.inputs]
  exclude = [
    # By file Path
    './public/countries/',
    './public/404.html',
    './public/401/',
    './public/style-guide/',
    './public/admin/',
    './public/buy-content/new-releaseszzzz/',
    './public/buy-content/buy-content-from-us/',
    './public/articles/',
    './public/find-a-reporter-2/',
    './public/find-a-reporter-copy/',
    './public/newtest/',
    './public/faqs/',
    './public/faqs/',
    './public/genres/',
    './public/producers/',
    './public/tags/'
  ]


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/feed"
  to = "https://18degreesnorthtv.substack.com/feed"
  status = 200
  force = true

[[redirects]]
  from = "/blog/*"
  to = "https://in435343.wordpress.com/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/fraction-cto/*"
  to = "https://incrementic.com/fractional-cto"
  status = 301
  force = true
  

[[redirects]]
  from = "/contact/davidbain.vcf"
  to = "/contact/davidbain.vcf"
  status = 200
  force = true

[[redirects]]
  from = "/slink/*"
  to = "https://18degreesnorthtv.substack.com/p/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/product-team-quiz"
  to = "https://david-tgdtta1o.scoreapp.com/"
  status = 301
  force = true

[[redirects]]
  from = "/calendar"
  to = "https://calendly.com/incrementic"
  status = 301
  force = true

[[redirects]]
  from = "/AudienceContentCraft"
  to = "https://bigin.zoho.com/crm/WebFormServeServlet?rid=2c1ba3dd5ab1bf5217c28cbaa41089a38a900384fad241ff0acfaad0af15ea8c0adc66efb95555204c1be882f832566cgid7e15e6bc29d7d91ff7765aae847f1bbd28fe71e109f7dbf38bef87ffc85d45a3"
  status = 301
  force = true


[[redirects]]
  from = "/*"
  to = "https://incrementic.webflow.io/:splat"
  status = 200
  force = true
