[build]
publish = "public"
command = "./build.sh"
functions = "functions"


[[plugins]]
package = "@netlify/plugin-sitemap"

 [plugins.inputs]
  exclude = [
    # By file Path
    './public/countries/',
    './public/404.html',
    './public/401/',
    './public/style-guide/',
    './public/admin/',
    './public/buy-content/new-releaseszzzz/',
    './public/buy-content/buy-content-from-us/',
    './public/articles/',
    './public/find-a-reporter-2/',
    './public/find-a-reporter-copy/',
    './public/newtest/',
    './public/faqs/',
    './public/faqs/',
    './public/genres/',
    './public/producers/',
    './public/tags/'
  ]


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/feed"
  to = "https://18degreesnorthtv.substack.com/feed"
  status = 200
  force = true

[[redirects]]
  from = "/blog/*"
  to = "https://in435343.wordpress.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/contact/davidbain.vcf"
  to = "/contact/davidbain.vcf"
  status = 200
  force = true

[[redirects]]
  from = "/slink/*"
  to = "https://18degreesnorthtv.substack.com/p/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/product-team-quiz"
  to = "https://david-ljbraakl.scoreapp.com/"
  status = 301
  force = true

[[redirects]]
  from = "/calendar"
  to = "https://calendly.com/incrementic"
  status = 301
  force = true


[[redirects]]
  from = "/*"
  to = "https://incrementic.webflow.io/:splat"
  status = 200
  force = true
